# Plugins.
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

# Theme.
set -g @catppuccin_flavour 'mocha'

# So mouse works when using vim.
set -g mouse on

# Start zsh instead of bash.
set -g default-command 'zsh'

# For clearning the screen and the buffer. `-n` is an alias for `-T root` which means
# that the prefix does not need to be passed, that is, no need to do C-b C-y, instead
# you can do C-y directly if you pass `-n`.
#
# NOTE: Ideally should be aligned with the same key binding happening from the shell
# tmux runs in, for instance, running C-y outside tmux should also clear history if you
# want to be consistent. I usually run shells without tmux.
bind -n C-y clear-history

# More history.
set-option -g history-limit 50000

# Use vim keybindings in copy mode.
set-window-option -g mode-keys vi

# Vim-style selecting and copying.
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer

# How is default-terminal compared to tmux terminal-overrides
#
#  https://unix.stackexchange.com/q/568260
#
# https://wiki.archlinux.org/title/tmux#256_color
set -g default-terminal 'xterm-256color'

# https://wiki.archlinux.org/title/tmux#24-bit_color
set -ga terminal-overrides ',xterm-256color:Tc'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf).
run '~/.tmux/plugins/tpm/tpm'
