include ~/.config/themes/tokyo-night/extras/kitty/tokyonight_storm.conf

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16.0

remember_window_size  yes
initial_window_width  1270
initial_window_height 720
window_margin_width 22 2 0
hide_window_decorations titlebar-only
confirm_os_window_close 0
macos_quit_when_last_window_closed yes

background_opacity 1.0
background_blur 0

dynamic_background_opacity yes

allow_remote_control yes

map opt+a hide_macos_other_apps
map f1 remote_control load-config -o background_opacity=1.0 -o background_blur=0
map f2 remote_control load-config -o background_opacity=0.9 -o background_blur=0
map f3 remote_control load-config -o background_opacity=0.9 -o background_blur=15
map f4 remote_control load-config -o background_opacity=0.7 -o background_blur=15
map f5 remote_control load-config -o background_opacity=0.3 -o background_blur=30
map f6 remote_control load-config -o background_opacity=0.0 -o background_blur=64
map opt+cmd+f remote_control load-config -o hide_window_decorations=titlebar-and-corners
map opt+cmd+w remote_control load-config -o hide_window_decorations=titlebar-only

