gui:
  sidePanelWidth: 0.23
git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --line-numbers-left-format="" --line-numbers-right-format="| " --paging=never
customCommands:
  - key: "T"
    context: "commits"
    command: "GIT_COMMITTER_DATE=\"$(date)\" git commit --amend --date=\"now\" --reset-author --no-edit"
    description: "Reset commit date and author to current user"
